name: 粉丝计数器

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点=北京时间8点
  workflow_dispatch:     # 允许手动触发测试

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: pip install requests beautifulsoup4 pandas
    - run: python scraper.py
    - run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data.csv
        git commit -m "每日更新" || echo "无需提交"
        git push
